x-ros-common: &ros-common
  build:
    context: .
    dockerfile: Dockerfile
    args:
      USERNAME: ${ROS_USERNAME:-ros}
      USER_UID: 1000
      USER_GID: 1000
  network_mode: host
  environment:
    - ROS_DOMAIN_ID=0
    - ROS_LOCALHOST_ONLY=0
    - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
    - TURTLEBOT3_MODEL=${TURTLEBOT3_MODEL:-waffle}
    - DISPLAY=${DISPLAY:-:0}
    - QT_X11_NO_MITSHM=1
  volumes:
    - ./workspace:/home/${ROS_USERNAME:-ros}/workspace
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
  entrypoint: ["bash", "/home/${ROS_USERNAME:-ros}/workspace/scripts/ros_entrypoint.sh"]
  stdin_open: true
  tty: true

services:
  ros2_humble:
    <<: *ros-common
    container_name: mobile_robotics_ros2-humble
    # user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    command: []

  gazebo:
    <<: *ros-common
    container_name: mobile_robotics_gazebo
    command: ["ros2", "launch", "/home/${ROS_USERNAME:-ros}/workspace/scripts/turtlebot3_world_resilient.launch.py"]

  rviz:
    <<: *ros-common
    container_name: mobile_robotics_rviz
    command: ["rviz2"]

  matlab:
    build:
      context: .
      dockerfile: Dockerfile.matlab
      args:
        MATLAB_RELEASE: ${MATLAB_RELEASE:-R2024a}
        MATLAB_PRODUCT_LIST: ${MATLAB_PRODUCT_LIST:-MATLAB Simulink Computer_Vision_Toolbox Control_System_Toolbox Curve_Fitting_Toolbox Image_Processing_Toolbox Optimization_Toolbox Robotics_System_Toolbox ROS_Toolbox Statistics_and_Machine_Learning_Toolbox Symbolic_Math_Toolbox}
        MPM_ADDITIONAL_FLAGS: ${MPM_ADDITIONAL_FLAGS:-}
    image: mobile_robotics_matlab:${MATLAB_RELEASE:-R2024a}
    container_name: mobile_robotics_matlab
    shm_size: "1gb"
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
      # - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      # Set your license info before startup if needed.
      # Example: MLM_LICENSE_FILE=27000@your-license-server
      - MLM_LICENSE_FILE=${MLM_LICENSE_FILE:-}
    volumes:
      - ./workspace:/home/${ROS_USERNAME:-ros}/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    restart: "no"
    stdin_open: true
    tty: true
